In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("columns/out_0.csv", sep="⇧", engine="python", quotechar='"', on_bad_lines="warn")

Skipping line 48859: '⇧' expected after '"'
Skipping line 48860: '⇧' expected after '"'
Skipping line 48861: '⇧' expected after '"'

# Research

Проблемные столбцы (скорее всего не будем использовать):
- Столбцы по типу: "ΔHкип, кДж·моль−1"
- Столбцы использующиеся для группировки каких-либо значений по времени (месяцу, году и т.п.)
- Столбцы без имени
- Столбцы, название которых не имеет смысла (числа и т.п.)
- Аббревиатуры и сокращения

### Столбцы без названия = 13577
их можно отправить в тестовую выборку, чтобы не терять информацию. (нужно еще посмотреть, что внутри них обычно лежит)

### Без имени
можно в тест

## .mv-parser... = 1356
обрезать только осмысленный текст

---

In [3]:
df["column_name"].value_counts()

column_name
Год                         18355
Место                        7201
Роль                         6579
Команда                      5663
Название                     5453
                            ...
ΔHкип, кДж·моль−1               1
ΔHпл, кДж·моль−1                1
ρ, г/см³                        1
tпл, °C                         1
Описание в De Aedificiis        1
Name: count, Length: 37660, dtype: int64

## Столбцы без названия = 13577 (срез датасета, настоящее количество больше)

In [4]:
unnamed_columns = df["column_name"].apply(lambda x: str(x).startswith("Unnamed"))
df[unnamed_columns]

,table_id,column_id,column_name
2,dataset/Dataset/data/2863377/table_11_meta.json,0,Unnamed: 0
13,dataset/Dataset/data/4727026/table_0_meta.json,1,Unnamed: 1
17,dataset/Dataset/data/5212502/table_3_meta.json,0,Unnamed: 0
35,dataset/Dataset/data/6995744/table_0_meta.json,1,Unnamed: 1
257,dataset/Dataset/data/632307/table_0_meta.json,5,Unnamed: 5
...,...,...,...
413374,dataset/Dataset/data/1787561/table_22_meta.json,17,Unnamed: 17
413387,dataset/Dataset/data/730442/table_14_meta.json,12,Unnamed: 12
413388,dataset/Dataset/data/730442/table_14_meta.json,13,Unnamed: 13
413389,dataset/Dataset/data/730442/table_14_meta.json,14,Unnamed: 14
413409,dataset/Dataset/data/3217640/table_3_meta.json,0,Unnamed: 0

In [5]:
unnamed_columns.sum()

13577

## Столбцы содержащие в названии: ".mw-parser..."

In [6]:
mv_parser = df["column_name"].apply(lambda x: str(x).strip().startswith(".mw-parser"))
df[mv_parser]

,table_id,column_id,column_name
63,dataset/Dataset/data/6573775/table_0_meta.json,16,.mw-parser-output .ts-comment-commentedText{bo...
426,dataset/Dataset/data/1793136/table_0_meta.json,5,.mw-parser-output .ts-comment-commentedText{bo...
610,dataset/Dataset/data/6558206/table_1_meta.json,0,.mw-parser-output .ts-comment-commentedText{bo...
757,dataset/Dataset/data/800584/table_2_meta.json,0,.mw-parser-output .ts-comment-commentedText{bo...
889,dataset/Dataset/data/5446712/table_1_meta.json,0,.mw-parser-output .ts-comment-commentedText{bo...
...,...,...,...
411479,dataset/Dataset/data/2906358/table_0_meta.json,0,.mw-parser-output .ts-comment-commentedText{bo...
411547,dataset/Dataset/data/8628454/table_0_meta.json,0,.mw-parser-output .ts-comment-commentedText{bo...
411560,dataset/Dataset/data/6210693/table_0_meta.json,0,.mw-parser-output .ts-comment-commentedText{bo...
412410,dataset/Dataset/data/5188724/table_1_meta.json,0,.mw-parser-output .ts-comment-commentedText{bo...
413440,dataset/Dataset/data/3818327/table_0_meta.json,0,.mw-parser-output .ts-comment-commentedText{bo...

### В назнваниях столбца содержится человекопонятное название, нужно отчистить мусорную информацию

In [7]:
df[mv_parser]["column_name"].unique()

array(['.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}Поз.',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}И',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}М',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}№',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}Pos.',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}В',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}Пр.',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}П.',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}} В',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}Категория',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}Коэфф.',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}Пропущено',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}03/04',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}Жертвы',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}И.',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}#',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}П',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}Оценка D',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}No.',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}Σ',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}СКР (общий)',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}Прим.',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}ЖК',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}ХП',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}Поз',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}\xa0В',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}№ п/п',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}Лига',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}Ист.',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}SP',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}SP.1',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}СС',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}КН',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}Кубок',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}Дата рождения',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}ТТХ',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}Древн.',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}PPG',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}СЭ',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}А',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}Участия в Рестлманиях',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}СУ',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}Уров.',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}MVP',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}З',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}Должность / Титул',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}№№',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}ГП[69]',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}Л/круги',
       '.mw-parser-output .ts-Родственные_проекты{width:19em;box-sizing:border-box;margin:0 0 .5em 1em;padding:.4em;background:#f8f9fa;border:1px solid #a2a9b1;font-size:90%}.mw-parser-output .ts-Родственные_проекты-header{margin-bottom:.2em;padding:.2em .6em;font-size:110%}.mw-parser-output .ts-Родственные_проекты-item{display:flex;padding:.2em .6em}.mw-parser-output .ts-Родственные_проекты-image{min-width:24px;display:inline-block;margin-right:.4em;flex:none;vertical-align:top;text-align:center}.mw-parser-output .ts-Родственные_проекты-image img{vertical-align:middle}.mw-parser-output .ts-Родственные_проекты-label{align-self:center}@media(max-width:719px){.mw-parser-output .ts-Родственные_проекты{width:auto;margin-left:0;margin-right:0}}Медиафайлы на\xa0ВикискладеМодель',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}Место',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}Пал.',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}ЧР',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}Всего депутатов',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}ГП[67]',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}Д / В',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}Б/Н',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}С',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}В–П',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}И, С',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}} И',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}Кат.',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}Субъект РФ',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}Звание',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}КИ',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}Рез.',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}Количество платных показов (млн)',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}12/13',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}Л/Круги',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}Ист',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}д/г',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}МГ',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}Дата',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}HP',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}Гр.',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}RPG',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}Сезоны',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}Л.круги',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}Конф.',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}Сн.',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}+/- (в\xa0%)',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}Быстрый круг',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}Плотность(чел./км²)',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}БК',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}ПП',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}Результат',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}Доля, %',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}КП',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}ТА (БК торпед)',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}Кат',
       '.mw-parser-output .ts-comment-commentedText{border-bottom:1px dotted;cursor:help}@media(hover:none){.mw-parser-output .ts-comment-commentedText:not(.rt-commentedText){border-bottom:0;cursor:auto}}Возраст',

In [8]:
mv_parser_humnareadable_names = df[mv_parser]["column_name"].apply(lambda x: str(x).split("}")[-1])
mv_parser_humnareadable_names.unique()

array(['Поз.', 'И', 'М', '№', 'Pos.', 'В', 'Пр.', 'П.', ' В', 'Категория',
       'Коэфф.', 'Пропущено', '03/04', 'Жертвы', 'И.', '#', 'П',
       'Оценка D', 'No.', 'Σ', 'СКР (общий)', 'Прим.', 'ЖК', 'ХП', 'Поз',
       '\xa0В', '№ п/п', 'Лига', 'Ист.', 'SP', 'SP.1', 'СС', 'КН',
       'Кубок', 'Дата рождения', 'ТТХ', 'Древн.', 'PPG', 'СЭ', 'А',
       'Участия в Рестлманиях', 'СУ', 'Уров.', 'MVP', 'З',
       'Должность / Титул', '№№', 'ГП[69]', 'Л/круги',
       'Медиафайлы на\xa0ВикискладеМодель', 'Место', 'Пал.', 'ЧР',
       'Всего депутатов', 'ГП[67]', 'Д / В', 'Б/Н', 'С', 'В–П', 'И, С',
       ' И', 'Кат.', 'Субъект РФ', 'Звание', 'КИ', 'Рез.',
       'Количество платных показов (млн)', '12/13', 'Л/Круги', 'Ист',
       'д/г', 'МГ', 'Дата', 'HP', 'Гр.', 'RPG', 'Сезоны', 'Л.круги',
       'Конф.', 'Сн.', '+/- (в\xa0%)', 'Быстрый круг',
       'Плотность(чел./км²)', 'БК', 'ПП', 'Результат', 'Доля, %', 'КП',
       'ТА (БК торпед)', 'Кат', 'Возраст', 'Н', '06/07', '15+15 км',
       'Рег. чемп.', 'СК', 'Pld', 'Минут', 'RCT', 'Игр', 'TFP', '96/97',
       'Коэф.', 'Год', 'Тренер', 'Возд.', 'ПСЛ', 'Зрители',
       'Название в заявкена номинацию', 'Сгр', 'Д/г', 'Доступ-ность', 'C',
       '14/15', 'Этап', 'Кандзи', 'Портрет', 'Country Songs[A]',
       'Год, ссылки,(№ церемонии)', 'Дом.', 'Также вышел', 'РС', '04/05',
       'МС', 'Bib', 'G', 'Раз', 'Дата пожалования', 'Депонирование[4]',
       'Синяя сторона'], dtype=object)

## Аббревиатуры / сокращения / меры (кг, кдж.)

In [9]:
# TODO: what should i do? -_-

# Очистка данных

1. Добавление столбца, содержащего первое слово в названии столбца
2. Очистка мусора из столбцов, содержащих ".mv-parser.."
3. Очистка символов (оставить только буквы алфавита а-яА-Я)
4. Столбцы без названия выделить в тестовую выборку (столбцы для которых нет в vocabulary w2v, тоже в тест)
---

In [10]:
df_cleansed = df.copy()

## 1. Очистка мусора из столбцов

In [11]:
def clean_mv_parser(col_name: str) -> str:
    if col_name.strip().startswith(".mw-parser"):
        return col_name.split("}")[-1]
    return col_name

df_cleansed.loc[:, "column_name"] = df_cleansed["column_name"].apply(lambda x: clean_mv_parser(str(x)))

In [12]:
df_cleansed[mv_parser]
# df_cleansed[~mv_parser]

                                              table_id  column_id column_name
63      dataset/Dataset/data/6573775/table_0_meta.json         16        Поз.
426     dataset/Dataset/data/1793136/table_0_meta.json          5           И
610     dataset/Dataset/data/6558206/table_1_meta.json          0           М
757      dataset/Dataset/data/800584/table_2_meta.json          0           М
889     dataset/Dataset/data/5446712/table_1_meta.json          0           М
...                                                ...        ...         ...
411479  dataset/Dataset/data/2906358/table_0_meta.json          0           М
411547  dataset/Dataset/data/8628454/table_0_meta.json          0           М
411560  dataset/Dataset/data/6210693/table_0_meta.json          0           М
412410  dataset/Dataset/data/5188724/table_1_meta.json          0           М
413440  dataset/Dataset/data/3818327/table_0_meta.json          0           М

[1356 rows x 3 columns]

## 2. Добавление столбца с первым словом в названии столбца

In [13]:
df_cleansed['first_word'] = df_cleansed["column_name"].apply(lambda x: str(x).split(" ")[0].lower())
df_cleansed["first_word"]

0                  чарт
1         высшаяпозиция
2              unnamed:
3               команда
4                     и
              ...
413473             дата
413474             дата
413475             дата
413476             дата
413477             дата
Name: first_word, Length: 413478, dtype: object

## 3. Очистка символов (оставляем только буквы)

In [14]:
def remove_non_alphabetic_symbols(col_name: str) -> str:
    return "".join(c for c in col_name if c.isalpha())

df_cleansed["first_word"] = df_cleansed["first_word"].apply(lambda x: remove_non_alphabetic_symbols(str(x)))
df_cleansed

,table_id,column_id,column_name,first_word
0,dataset/Dataset/data/7779522/table_0_meta.json,0,Чарт (2019),чарт
1,dataset/Dataset/data/7779522/table_0_meta.json,1,Высшаяпозиция,высшаяпозиция
2,dataset/Dataset/data/2863377/table_11_meta.json,0,Unnamed: 0,unnamed
3,dataset/Dataset/data/2863377/table_11_meta.json,1,Команда,команда
4,dataset/Dataset/data/2863377/table_11_meta.json,2,И,и
...,...,...,...,...
413473,dataset/Dataset/data/35185/table_6_meta.json,2,Дата получения Любекского права,дата
413474,dataset/Dataset/data/35185/table_6_meta.json,3,Дата получения Кульмского права,дата
413475,dataset/Dataset/data/35185/table_6_meta.json,4,Дата получения Магдебургского права,дата
413476,dataset/Dataset/data/35185/table_6_meta.json,5,Дата вступления в союз,дата
413477,dataset/Dataset/data/35185/table_6_meta.json,6,Дата выхода из союза,дата

## 4. Выделение столбцов без названия

In [15]:
unnamed_columns = df_cleansed["first_word"] == "unnamed"
df_cleansed[unnamed_columns]

,table_id,column_id,column_name,first_word
2,dataset/Dataset/data/2863377/table_11_meta.json,0,Unnamed: 0,unnamed
13,dataset/Dataset/data/4727026/table_0_meta.json,1,Unnamed: 1,unnamed
17,dataset/Dataset/data/5212502/table_3_meta.json,0,Unnamed: 0,unnamed
35,dataset/Dataset/data/6995744/table_0_meta.json,1,Unnamed: 1,unnamed
257,dataset/Dataset/data/632307/table_0_meta.json,5,Unnamed: 5,unnamed
...,...,...,...,...
413374,dataset/Dataset/data/1787561/table_22_meta.json,17,Unnamed: 17,unnamed
413387,dataset/Dataset/data/730442/table_14_meta.json,12,Unnamed: 12,unnamed
413388,dataset/Dataset/data/730442/table_14_meta.json,13,Unnamed: 13,unnamed
413389,dataset/Dataset/data/730442/table_14_meta.json,14,Unnamed: 14,unnamed
413409,dataset/Dataset/data/3217640/table_3_meta.json,0,Unnamed: 0,unnamed

In [16]:
df_cleansed = df_cleansed[~unnamed_columns]
df_cleansed

,table_id,column_id,column_name,first_word
0,dataset/Dataset/data/7779522/table_0_meta.json,0,Чарт (2019),чарт
1,dataset/Dataset/data/7779522/table_0_meta.json,1,Высшаяпозиция,высшаяпозиция
3,dataset/Dataset/data/2863377/table_11_meta.json,1,Команда,команда
4,dataset/Dataset/data/2863377/table_11_meta.json,2,И,и
5,dataset/Dataset/data/2863377/table_11_meta.json,3,В,в
...,...,...,...,...
413473,dataset/Dataset/data/35185/table_6_meta.json,2,Дата получения Любекского права,дата
413474,dataset/Dataset/data/35185/table_6_meta.json,3,Дата получения Кульмского права,дата
413475,dataset/Dataset/data/35185/table_6_meta.json,4,Дата получения Магдебургского права,дата
413476,dataset/Dataset/data/35185/table_6_meta.json,5,Дата вступления в союз,дата
413477,dataset/Dataset/data/35185/table_6_meta.json,6,Дата выхода из союза,дата

# Лемматизация (оооочень медленно, не делаю, пока не найду способ быстрее сделать)

In [17]:
import spacy
nlp = spacy.load("ru_core_news_sm", disable=['parser', 'ner'])

In [18]:
doc = nlp("Даты")
doc[0].lemma_

'дата'

In [19]:
""" Too slow
def lemmatize_first_word(first_word: str) -> str:
    try:
        return nlp(first_word)[0].lemma_
    except IndexError:
        return first_word

df_cleansed["first_word"].apply(lemmatize_first_word)
"""

' Too slow\ndef lemmatize_first_word(first_word: str) -> str:\n    try:\n        return nlp(first_word)[0].lemma_\n    except IndexError:\n        return first_word\n\ndf_cleansed["first_word"].apply(lemmatize_first_word)\n'

# Создание ембеддингов

Для кластеризации удаляю столбцы, для которых не было получено ембеддингов

In [20]:
import gensim.downloader

ru_model = gensim.downloader.load("word2vec-ruscorpora-300")

In [21]:
def get_embedding(word: str) -> list|None:
    try:
        return ru_model.__getitem__([f"{word}_NOUN"])
    except KeyError:
        return None

df_cleansed["embedding"] = df_cleansed["first_word"].apply(get_embedding)
df_cleansed

/tmp/ipykernel_80155/1837533370.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleansed["embedding"] = df_cleansed["first_word"].apply(get_embedding)

,table_id,column_id,column_name,first_word,embedding
0,dataset/Dataset/data/7779522/table_0_meta.json,0,Чарт (2019),чарт,"[[0.029721806, 0.03733756, -0.05228397, 0.0204..."
1,dataset/Dataset/data/7779522/table_0_meta.json,1,Высшаяпозиция,высшаяпозиция,None
3,dataset/Dataset/data/2863377/table_11_meta.json,1,Команда,команда,"[[0.05975376, -0.050061475, 0.025441337, 0.015..."
4,dataset/Dataset/data/2863377/table_11_meta.json,2,И,и,None
5,dataset/Dataset/data/2863377/table_11_meta.json,3,В,в,None
...,...,...,...,...,...
413473,dataset/Dataset/data/35185/table_6_meta.json,2,Дата получения Любекского права,дата,"[[0.11930524, 0.021293541, -0.06631852, -0.068..."
413474,dataset/Dataset/data/35185/table_6_meta.json,3,Дата получения Кульмского права,дата,"[[0.11930524, 0.021293541, -0.06631852, -0.068..."
413475,dataset/Dataset/data/35185/table_6_meta.json,4,Дата получения Магдебургского права,дата,"[[0.11930524, 0.021293541, -0.06631852, -0.068..."
413476,dataset/Dataset/data/35185/table_6_meta.json,5,Дата вступления в союз,дата,"[[0.11930524, 0.021293541, -0.06631852, -0.068..."
413477,dataset/Dataset/data/35185/table_6_meta.json,6,Дата выхода из союза,дата,"[[0.11930524, 0.021293541, -0.06631852, -0.068..."

In [22]:
df_prepared_for_v2w = df_cleansed[~df_cleansed['embedding'].isna()]
df_prepared_for_v2w

,table_id,column_id,column_name,first_word,embedding
0,dataset/Dataset/data/7779522/table_0_meta.json,0,Чарт (2019),чарт,"[[0.029721806, 0.03733756, -0.05228397, 0.0204..."
3,dataset/Dataset/data/2863377/table_11_meta.json,1,Команда,команда,"[[0.05975376, -0.050061475, 0.025441337, 0.015..."
8,dataset/Dataset/data/2863377/table_11_meta.json,6,ГЗ,гз,"[[-0.0009766041, 0.053358104, 0.020000864, 0.0..."
9,dataset/Dataset/data/2863377/table_11_meta.json,7,ГП,гп,"[[-0.0041590976, 0.0012636776, -0.05824213, 0...."
11,dataset/Dataset/data/2863377/table_11_meta.json,9,Очки,очки,"[[0.029941676, -0.03986928, 0.060400773, 0.034..."
...,...,...,...,...,...
413473,dataset/Dataset/data/35185/table_6_meta.json,2,Дата получения Любекского права,дата,"[[0.11930524, 0.021293541, -0.06631852, -0.068..."
413474,dataset/Dataset/data/35185/table_6_meta.json,3,Дата получения Кульмского права,дата,"[[0.11930524, 0.021293541, -0.06631852, -0.068..."
413475,dataset/Dataset/data/35185/table_6_meta.json,4,Дата получения Магдебургского права,дата,"[[0.11930524, 0.021293541, -0.06631852, -0.068..."
413476,dataset/Dataset/data/35185/table_6_meta.json,5,Дата вступления в союз,дата,"[[0.11930524, 0.021293541, -0.06631852, -0.068..."
413477,dataset/Dataset/data/35185/table_6_meta.json,6,Дата выхода из союза,дата,"[[0.11930524, 0.021293541, -0.06631852, -0.068..."

In [23]:
embeddings = df_prepared_for_v2w['embedding']
embeddings

0         [[0.029721806, 0.03733756, -0.05228397, 0.0204...
3         [[0.05975376, -0.050061475, 0.025441337, 0.015...
8         [[-0.0009766041, 0.053358104, 0.020000864, 0.0...
9         [[-0.0041590976, 0.0012636776, -0.05824213, 0....
11        [[0.029941676, -0.03986928, 0.060400773, 0.034...
                                ...
413473    [[0.11930524, 0.021293541, -0.06631852, -0.068...
413474    [[0.11930524, 0.021293541, -0.06631852, -0.068...
413475    [[0.11930524, 0.021293541, -0.06631852, -0.068...
413476    [[0.11930524, 0.021293541, -0.06631852, -0.068...
413477    [[0.11930524, 0.021293541, -0.06631852, -0.068...
Name: embedding, Length: 210777, dtype: object

# Кластеризация

- DBScan O(n^2) + съедает ресурсы, не подходит для датасета.
- Использую mini batch k-means

Можно улучшить, взяв параллельный k-means на cuda https://github.com/src-d/kmcuda

In [24]:
from sklearn.cluster import MiniBatchKMeans
import numpy as np

In [25]:
# 191318 x 300
embeddings_reshaped = embeddings.to_numpy()
embeddings_reshaped = np.array(list(map(lambda x: x[0], embeddings_reshaped)))
embeddings_reshaped.shape

(210777, 300)

In [26]:
num_clusters = 110
kmeans = MiniBatchKMeans(n_clusters=num_clusters, random_state=13)

In [27]:
df_prepared_for_v2w["cls"] = kmeans.fit_predict(embeddings_reshaped)

/home/kirilltobola/Dev/github.com/isp/cta/venv/lib/python3.11/site-packages/sklearn/cluster/_kmeans.py:1934: FutureWarning: The default value of `n_init` will change from 3 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=3)
/tmp/ipykernel_80155/3291261708.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_prepared_for_v2w["cls"] = kmeans.fit_predict(embeddings_reshaped)

In [28]:
from random import randint

df_prepared_for_v2w[df_prepared_for_v2w['cls'] == randint(0, num_clusters - 1)]

,table_id,column_id,column_name,first_word,embedding,cls
1032,dataset/Dataset/data/745354/table_22_meta.json,3,Факультет,факультет,"[[-0.022686634, 0.042891286, -0.03649195, -0.0...",48
1039,dataset/Dataset/data/745354/table_50_meta.json,3,Факультет,факультет,"[[-0.022686634, 0.042891286, -0.03649195, -0.0...",48
1045,dataset/Dataset/data/745354/table_30_meta.json,3,Факультет,факультет,"[[-0.022686634, 0.042891286, -0.03649195, -0.0...",48
1848,dataset/Dataset/data/939411/table_20_meta.json,3,Факультет,факультет,"[[-0.022686634, 0.042891286, -0.03649195, -0.0...",48
1861,dataset/Dataset/data/939411/table_52_meta.json,3,Факультет,факультет,"[[-0.022686634, 0.042891286, -0.03649195, -0.0...",48
...,...,...,...,...,...,...
410166,dataset/Dataset/data/397861/table_35_meta.json,3,Факультет,факультет,"[[-0.022686634, 0.042891286, -0.03649195, -0.0...",48
410172,dataset/Dataset/data/397861/table_41_meta.json,3,Факультет,факультет,"[[-0.022686634, 0.042891286, -0.03649195, -0.0...",48
411573,dataset/Dataset/data/3565199/table_43_meta.json,3,Факультет,факультет,"[[-0.022686634, 0.042891286, -0.03649195, -0.0...",48
411585,dataset/Dataset/data/3565199/table_18_meta.json,3,Факультет,факультет,"[[-0.022686634, 0.042891286, -0.03649195, -0.0...",48
412164,dataset/Dataset/data/626109/table_20_meta.json,3,Факультет,факультет,"[[-0.022686634, 0.042891286, -0.03649195, -0.0...",48