In [1]:
import pandas as pd

from tqdm import tqdm
tqdm.pandas()

import gensim.downloader
import numpy as np

from pathlib import Path

import glob
import re

# Создание конечного датафрейма

In [2]:
# columns_data_path = "./collecting/columns_data.csv"
# if not Path(columns_data_path).exists():
#     raise Exception("columns_data.csv doesnt exist. Run `make; ./collect_columns_data` from this dir.")

# df_data = pd.read_csv(f"columns_data.csv", sep="⇧", engine="python", quotechar='"', on_bad_lines="warn")

In [3]:
import pandas as pd
import glob

df_list = []

number_of_chunks = len(glob.glob("../collecting/columns_data/data*.csv"))
for i in range(number_of_chunks):
    df_list.append(
        pd.read_csv(f"../collecting/columns_data/data_{i}.csv", sep="⇧", engine="python", quotechar='"', on_bad_lines="warn")
    )

df_data = pd.concat(df_list, axis=0)

Skipping line 708: '⇧' expected after '"'
Skipping line 6668: '⇧' expected after '"'
Skipping line 7141: '⇧' expected after '"'
Skipping line 8661: '⇧' expected after '"'
Skipping line 8863: field larger than field limit (131072)
Skipping line 9233: '⇧' expected after '"'
Skipping line 11144: '⇧' expected after '"'
Skipping line 11923: '⇧' expected after '"'
Skipping line 12338: '⇧' expected after '"'
Skipping line 13211: '⇧' expected after '"'
Skipping line 16581: '⇧' expected after '"'
Skipping line 16602: '⇧' expected after '"'
Skipping line 17339: '⇧' expected after '"'
Skipping line 17516: '⇧' expected after '"'
Skipping line 18088: '⇧' expected after '"'
Skipping line 20082: '⇧' expected after '"'
Skipping line 20495: '⇧' expected after '"'
Skipping line 20799: '⇧' expected after '"'
Skipping line 21002: '⇧' expected after '"'
Skipping line 23813: '⇧' expected after '"'
Skipping line 24086: '⇧' expected after '"'
Skipping line 24153: '⇧' expected after '"'
Skipping line 25834: '⇧' expected after '"'
Skipping line 25992: '⇧' expected after '"'
Skipping line 26155: '⇧' expected after '"'
Skipping line 28555: '⇧' expected after '"'
Skipping line 28873: '⇧' expected after '"'
Skipping line 29189: '⇧' expected after '"'
Skipping line 30879: '⇧' expected after '"'
Skipping line 31362: '⇧' expected after '"'
Skipping line 32873: '⇧' expected after '"'
Skipping line 33341: '⇧' expected after '"'
Skipping line 33343: '⇧' expected after '"'
Skipping line 34686: '⇧' expected after '"'
Skipping line 35465: '⇧' expected after '"'
Skipping line 36867: '⇧' expected after '"'
Skipping line 36875: '⇧' expected after '"'
Skipping line 37258: '⇧' expected after '"'
Skipping line 37976: '⇧' expected after '"'
Skipping line 40531: '⇧' expected after '"'
Skipping line 40610: '⇧' expected after '"'
Skipping line 40883: '⇧' expected after '"'
Skipping line 41345: '⇧' expected after '"'
Skipping line 42892: '⇧' expected after '"'
Skipping line 43790: '⇧' expected after '"'
Skipping line 44606: '⇧' expected after '"'
Skipping line 44945: '⇧' expected after '"'
Skipping line 47205: '⇧' expected after '"'
Skipping line 47535: '⇧' expected after '"'
Skipping line 48173: '⇧' expected after '"'
Skipping line 50127: '⇧' expected after '"'
Skipping line 50130: '⇧' expected after '"'
Skipping line 50810: '⇧' expected after '"'
Skipping line 51457: '⇧' expected after '"'
Skipping line 53659: '⇧' expected after '"'
Skipping line 53960: '⇧' expected after '"'
Skipping line 55685: '⇧' expected after '"'
Skipping line 57025: '⇧' expected after '"'
Skipping line 57391: '⇧' expected after '"'
Skipping line 57452: '⇧' expected after '"'
Skipping line 57759: '⇧' expected after '"'
Skipping line 58338: '⇧' expected after '"'
Skipping line 59201: field larger than field limit (131072)
Skipping line 59836: '⇧' expected after '"'
Skipping line 61612: '⇧' expected after '"'
Skipping line 61613: '⇧' expected after '"'
Skipping line 64011: '⇧' expected after '"'
Skipping line 64279: '⇧' expected after '"'
Skipping line 64807: '⇧' expected after '"'
Skipping line 65768: '⇧' expected after '"'
Skipping line 68026: '⇧' expected after '"'
Skipping line 68460: '⇧' expected after '"'
Skipping line 69940: '⇧' expected after '"'
Skipping line 71917: '⇧' expected after '"'
Skipping line 73976: '⇧' expected after '"'
Skipping line 73990: '⇧' expected after '"'
Skipping line 73998: '⇧' expected after '"'
Skipping line 74560: '⇧' expected after '"'
Skipping line 75284: '⇧' expected after '"'
Skipping line 76925: '⇧' expected after '"'
Skipping line 77627: '⇧' expected after '"'
Skipping line 77959: '⇧' expected after '"'
Skipping line 78659: '⇧' expected after '"'
Skipping line 78858: '⇧' expected after '"'
Skipping line 78934: '⇧' expected after '"'
Skipping line 78972: '⇧' expected after '"'
Skipping line 79002: '⇧' expected after '"'
Skipping line 79527: '⇧' expected after '"'
Skipping line 79861: '⇧' expected after '"'
Skipping line 80671: '⇧' expected after '"'
Skipping line 80847: '⇧' expected after '"'
Skipping line 81521: '⇧' expected after '"'
Skipping line 81544: '⇧' expected after '"'
Skipping line 81547: '⇧' expected after '"'
Skipping line 82256: '⇧' expected after '"'
Skipping line 82301: '⇧' expected after '"'
Skipping line 82302: '⇧' expected after '"'
Skipping line 82878: '⇧' expected after '"'
Skipping line 83365: '⇧' expected after '"'
Skipping line 83367: '⇧' expected after '"'
Skipping line 84877: '⇧' expected after '"'
Skipping line 85406: '⇧' expected after '"'
Skipping line 85432: '⇧' expected after '"'
Skipping line 86877: '⇧' expected after '"'
Skipping line 86885: '⇧' expected after '"'
Skipping line 87998: '⇧' expected after '"'
Skipping line 89601: '⇧' expected after '"'
Skipping line 89667: '⇧' expected after '"'
Skipping line 89743: '⇧' expected after '"'
Skipping line 90136: '⇧' expected after '"'
Skipping line 92201: '⇧' expected after '"'
Skipping line 92557: '⇧' expected after '"'
Skipping line 92987: '⇧' expected after '"'
Skipping line 94879: '⇧' expected after '"'
Skipping line 95217: '⇧' expected after '"'
Skipping line 95910: '⇧' expected after '"'
Skipping line 96317: '⇧' expected after '"'
Skipping line 96380: '⇧' expected after '"'
Skipping line 97060: '⇧' expected after '"'
Skipping line 98313: '⇧' expected after '"'
Skipping line 100217: '⇧' expected after '"'
Skipping line 100395: '⇧' expected after '"'
Skipping line 101221: '⇧' expected after '"'
Skipping line 101540: '⇧' expected after '"'
Skipping line 101708: '⇧' expected after '"'
Skipping line 101821: '⇧' expected after '"'
Skipping line 101849: '⇧' expected after '"'
Skipping line 102735: '⇧' expected after '"'
Skipping line 103468: '⇧' expected after '"'
Skipping line 103854: '⇧' expected after '"'
Skipping line 103885: '⇧' expected after '"'
Skipping line 104170: '⇧' expected after '"'
Skipping line 105172: '⇧' expected after '"'
Skipping line 106111: '⇧' expected after '"'
Skipping line 106340: '⇧' expected after '"'
Skipping line 107770: '⇧' expected after '"'
Skipping line 109125: '⇧' expected after '"'
Skipping line 109256: '⇧' expected after '"'
Skipping line 109623: '⇧' expected after '"'
Skipping line 112619: '⇧' expected after '"'
Skipping line 112879: '⇧' expected after '"'
Skipping line 112896: '⇧' expected after '"'
Skipping line 112984: '⇧' expected after '"'
Skipping line 113527: '⇧' expected after '"'
Skipping line 113615: '⇧' expected after '"'
Skipping line 113890: '⇧' expected after '"'
Skipping line 114830: '⇧' expected after '"'
Skipping line 114992: '⇧' expected after '"'
Skipping line 115596: '⇧' expected after '"'
Skipping line 116256: '⇧' expected after '"'
Skipping line 116277: '⇧' expected after '"'
Skipping line 118143: '⇧' expected after '"'
Skipping line 118724: '⇧' expected after '"'
Skipping line 118944: '⇧' expected after '"'
Skipping line 119529: '⇧' expected after '"'
Skipping line 119890: '⇧' expected after '"'
Skipping line 120587: '⇧' expected after '"'
Skipping line 120815: '⇧' expected after '"'
Skipping line 120842: '⇧' expected after '"'
Skipping line 120945: '⇧' expected after '"'
Skipping line 121042: '⇧' expected after '"'
Skipping line 123104: '⇧' expected after '"'
Skipping line 696: '⇧' expected after '"'
Skipping line 3708: '⇧' expected after '"'
Skipping line 4777: '⇧' expected after '"'
Skipping line 5858: '⇧' expected after '"'
Skipping line 6217: '⇧' expected after '"'
Skipping line 7826: '⇧' expected after '"'
Skipping line 8734: '⇧' expected after '"'
Skipping line 8762: '⇧' expected after '"'
Skipping line 9356: '⇧' expected after '"'
Skipping line 10285: '⇧' expected after '"'
Skipping line 10370: '⇧' expected after '"'
Skipping line 11163: '⇧' expected after '"'
Skipping line 12420: '⇧' expected after '"'
Skipping line 13552: '⇧' expected after '"'
Skipping line 14114: '⇧' expected after '"'
Skipping line 14842: '⇧' expected after '"'
Skipping line 15049: '⇧' expected after '"'
Skipping line 17038: '⇧' expected after '"'
Skipping line 17510: '⇧' expected after '"'
Skipping line 17696: '⇧' expected after '"'
Skipping line 20039: '⇧' expected after '"'
Skipping line 20138: '⇧' expected after '"'
Skipping line 20377: '⇧' expected after '"'
Skipping line 23516: '⇧' expected after '"'
Skipping line 25232: '⇧' expected after '"'
Skipping line 25837: '⇧' expected after '"'
Skipping line 26166: '⇧' expected after '"'
Skipping line 27482: '⇧' expected after '"'
Skipping line 27824: '⇧' expected after '"'
Skipping line 27902: '⇧' expected after '"'
Skipping line 27903: '⇧' expected after '"'
Skipping line 28146: '⇧' expected after '"'
Skipping line 28151: '⇧' expected after '"'
Skipping line 28233: '⇧' expected after '"'
Skipping line 31759: '⇧' expected after '"'
Skipping line 33413: '⇧' expected after '"'
Skipping line 34113: '⇧' expected after '"'
Skipping line 35903: '⇧' expected after '"'
Skipping line 36948: '⇧' expected after '"'
Skipping line 37640: '⇧' expected after '"'
Skipping line 39898: '⇧' expected after '"'
Skipping line 44269: field larger than field limit (131072)
Skipping line 44446: '⇧' expected after '"'
Skipping line 44874: '⇧' expected after '"'
Skipping line 45949: '⇧' expected after '"'
Skipping line 46578: '⇧' expected after '"'
Skipping line 47313: '⇧' expected after '"'
Skipping line 48329: '⇧' expected after '"'
Skipping line 49643: '⇧' expected after '"'
Skipping line 51024: '⇧' expected after '"'
Skipping line 51224: '⇧' expected after '"'
Skipping line 51449: '⇧' expected after '"'
Skipping line 51687: '⇧' expected after '"'
Skipping line 51826: '⇧' expected after '"'
Skipping line 52552: '⇧' expected after '"'
Skipping line 54127: '⇧' expected after '"'
Skipping line 54381: '⇧' expected after '"'
Skipping line 54727: '⇧' expected after '"'
Skipping line 55599: '⇧' expected after '"'
Skipping line 56934: '⇧' expected after '"'
Skipping line 57021: '⇧' expected after '"'
Skipping line 57238: '⇧' expected after '"'
Skipping line 59329: '⇧' expected after '"'
Skipping line 60936: '⇧' expected after '"'
Skipping line 61212: '⇧' expected after '"'
Skipping line 61729: '⇧' expected after '"'
Skipping line 61730: '⇧' expected after '"'
Skipping line 62096: '⇧' expected after '"'
Skipping line 62291: '⇧' expected after '"'
Skipping line 62653: '⇧' expected after '"'
Skipping line 62825: '⇧' expected after '"'
Skipping line 63679: '⇧' expected after '"'
Skipping line 64944: '⇧' expected after '"'
Skipping line 66907: '⇧' expected after '"'
Skipping line 68467: '⇧' expected after '"'
Skipping line 70080: '⇧' expected after '"'
Skipping line 70375: '⇧' expected after '"'
Skipping line 70783: '⇧' expected after '"'
Skipping line 71074: '⇧' expected after '"'
Skipping line 72644: '⇧' expected after '"'
Skipping line 73104: '⇧' expected after '"'
Skipping line 73888: '⇧' expected after '"'
Skipping line 73926: '⇧' expected after '"'
Skipping line 73999: '⇧' expected after '"'
Skipping line 75859: '⇧' expected after '"'
Skipping line 76738: '⇧' expected after '"'
Skipping line 77137: '⇧' expected after '"'
Skipping line 77708: '⇧' expected after '"'
Skipping line 77808: '⇧' expected after '"'
Skipping line 77843: '⇧' expected after '"'
Skipping line 79087: '⇧' expected after '"'
Skipping line 79147: '⇧' expected after '"'
Skipping line 79152: '⇧' expected after '"'
Skipping line 79743: '⇧' expected after '"'
Skipping line 81778: '⇧' expected after '"'
Skipping line 83139: '⇧' expected after '"'
Skipping line 83379: '⇧' expected after '"'
Skipping line 84010: '⇧' expected after '"'
Skipping line 85288: '⇧' expected after '"'
Skipping line 85979: '⇧' expected after '"'
Skipping line 86233: '⇧' expected after '"'
Skipping line 89311: '⇧' expected after '"'
Skipping line 89751: '⇧' expected after '"'
Skipping line 90705: '⇧' expected after '"'
Skipping line 90765: '⇧' expected after '"'
Skipping line 91181: '⇧' expected after '"'
Skipping line 91425: '⇧' expected after '"'
Skipping line 92918: '⇧' expected after '"'
Skipping line 92933: '⇧' expected after '"'
Skipping line 94040: '⇧' expected after '"'
Skipping line 95000: '⇧' expected after '"'
Skipping line 96965: '⇧' expected after '"'
Skipping line 97458: '⇧' expected after '"'
Skipping line 98486: '⇧' expected after '"'
Skipping line 98628: '⇧' expected after '"'
Skipping line 98915: '⇧' expected after '"'
Skipping line 100982: '⇧' expected after '"'
Skipping line 103207: '⇧' expected after '"'
Skipping line 103891: '⇧' expected after '"'
Skipping line 104466: '⇧' expected after '"'
Skipping line 104467: '⇧' expected after '"'
Skipping line 106093: '⇧' expected after '"'
Skipping line 106109: '⇧' expected after '"'
Skipping line 107105: '⇧' expected after '"'
Skipping line 107288: '⇧' expected after '"'
Skipping line 107920: '⇧' expected after '"'
Skipping line 108322: '⇧' expected after '"'
Skipping line 108795: '⇧' expected after '"'
Skipping line 109501: '⇧' expected after '"'
Skipping line 110132: '⇧' expected after '"'
Skipping line 110562: '⇧' expected after '"'
Skipping line 111941: '⇧' expected after '"'
Skipping line 112280: '⇧' expected after '"'
Skipping line 112372: '⇧' expected after '"'
Skipping line 112636: '⇧' expected after '"'
Skipping line 113990: '⇧' expected after '"'
Skipping line 114342: '⇧' expected after '"'
Skipping line 114394: '⇧' expected after '"'
Skipping line 114617: '⇧' expected after '"'
Skipping line 114618: '⇧' expected after '"'
Skipping line 114875: '⇧' expected after '"'
Skipping line 116230: '⇧' expected after '"'
Skipping line 116231: '⇧' expected after '"'
Skipping line 117298: '⇧' expected after '"'
Skipping line 118331: '⇧' expected after '"'
Skipping line 118345: '⇧' expected after '"'
Skipping line 118374: '⇧' expected after '"'
Skipping line 119316: '⇧' expected after '"'
Skipping line 119750: '⇧' expected after '"'
Skipping line 119751: '⇧' expected after '"'
Skipping line 120270: '⇧' expected after '"'
Skipping line 121856: '⇧' expected after '"'
Skipping line 121868: '⇧' expected after '"'
Skipping line 121948: '⇧' expected after '"'
Skipping line 122055: '⇧' expected after '"'
Skipping line 122550: '⇧' expected after '"'
Skipping line 4396: '⇧' expected after '"'
Skipping line 4425: '⇧' expected after '"'
Skipping line 4501: '⇧' expected after '"'
Skipping line 5926: '⇧' expected after '"'
Skipping line 7164: '⇧' expected after '"'
Skipping line 7798: '⇧' expected after '"'
Skipping line 9383: '⇧' expected after '"'
Skipping line 9641: '⇧' expected after '"'
Skipping line 11227: '⇧' expected after '"'
Skipping line 15401: '⇧' expected after '"'
Skipping line 17924: '⇧' expected after '"'
Skipping line 18005: '⇧' expected after '"'
Skipping line 21382: '⇧' expected after '"'
Skipping line 21479: '⇧' expected after '"'
Skipping line 21887: '⇧' expected after '"'
Skipping line 23568: '⇧' expected after '"'
Skipping line 24811: '⇧' expected after '"'
Skipping line 25335: '⇧' expected after '"'
Skipping line 26388: '⇧' expected after '"'
Skipping line 27354: '⇧' expected after '"'
Skipping line 27389: '⇧' expected after '"'
Skipping line 27785: '⇧' expected after '"'
Skipping line 28013: '⇧' expected after '"'
Skipping line 28031: '⇧' expected after '"'
Skipping line 28701: '⇧' expected after '"'
Skipping line 28941: '⇧' expected after '"'
Skipping line 30254: '⇧' expected after '"'
Skipping line 32918: '⇧' expected after '"'
Skipping line 33831: '⇧' expected after '"'
Skipping line 34358: '⇧' expected after '"'
Skipping line 35651: '⇧' expected after '"'
Skipping line 41403: '⇧' expected after '"'
Skipping line 41716: '⇧' expected after '"'
Skipping line 41899: '⇧' expected after '"'
Skipping line 42283: '⇧' expected after '"'
Skipping line 45682: '⇧' expected after '"'
Skipping line 45939: '⇧' expected after '"'
Skipping line 47321: '⇧' expected after '"'
Skipping line 47802: '⇧' expected after '"'
Skipping line 48173: '⇧' expected after '"'
Skipping line 48248: '⇧' expected after '"'
Skipping line 50481: '⇧' expected after '"'
Skipping line 50664: '⇧' expected after '"'
Skipping line 51169: '⇧' expected after '"'
Skipping line 51999: '⇧' expected after '"'
Skipping line 52853: '⇧' expected after '"'
Skipping line 53405: '⇧' expected after '"'
Skipping line 54539: '⇧' expected after '"'
Skipping line 55102: '⇧' expected after '"'
Skipping line 56558: '⇧' expected after '"'
Skipping line 56841: '⇧' expected after '"'
Skipping line 57970: '⇧' expected after '"'
Skipping line 59527: '⇧' expected after '"'
Skipping line 59841: '⇧' expected after '"'
Skipping line 62048: '⇧' expected after '"'
Skipping line 62707: '⇧' expected after '"'
Skipping line 63937: '⇧' expected after '"'
Skipping line 63979: '⇧' expected after '"'
Skipping line 65396: '⇧' expected after '"'
Skipping line 67638: '⇧' expected after '"'
Skipping line 68384: '⇧' expected after '"'
Skipping line 69008: '⇧' expected after '"'
Skipping line 69238: '⇧' expected after '"'
Skipping line 69697: '⇧' expected after '"'
Skipping line 71200: '⇧' expected after '"'
Skipping line 72684: '⇧' expected after '"'
Skipping line 72814: '⇧' expected after '"'
Skipping line 73672: '⇧' expected after '"'
Skipping line 74565: '⇧' expected after '"'
Skipping line 74812: '⇧' expected after '"'
Skipping line 74898: '⇧' expected after '"'
Skipping line 74908: '⇧' expected after '"'
Skipping line 78492: '⇧' expected after '"'
Skipping line 78701: '⇧' expected after '"'
Skipping line 79557: '⇧' expected after '"'
Skipping line 79749: '⇧' expected after '"'
Skipping line 79867: '⇧' expected after '"'
Skipping line 82473: '⇧' expected after '"'
Skipping line 83214: '⇧' expected after '"'
Skipping line 83958: '⇧' expected after '"'
Skipping line 85979: '⇧' expected after '"'
Skipping line 86411: '⇧' expected after '"'
Skipping line 86855: '⇧' expected after '"'
Skipping line 87356: '⇧' expected after '"'
Skipping line 89065: '⇧' expected after '"'
Skipping line 89234: field larger than field limit (131072)
Skipping line 90021: '⇧' expected after '"'
Skipping line 90023: '⇧' expected after '"'
Skipping line 90695: '⇧' expected after '"'
Skipping line 90702: '⇧' expected after '"'
Skipping line 91556: '⇧' expected after '"'
Skipping line 92509: '⇧' expected after '"'
Skipping line 93304: '⇧' expected after '"'
Skipping line 93344: '⇧' expected after '"'
Skipping line 95028: '⇧' expected after '"'
Skipping line 95031: '⇧' expected after '"'
Skipping line 95588: '⇧' expected after '"'
Skipping line 95619: '⇧' expected after '"'
Skipping line 96264: '⇧' expected after '"'
Skipping line 96732: '⇧' expected after '"'
Skipping line 97754: '⇧' expected after '"'
Skipping line 97854: '⇧' expected after '"'
Skipping line 98814: '⇧' expected after '"'
Skipping line 99123: '⇧' expected after '"'
Skipping line 99426: '⇧' expected after '"'
Skipping line 100433: '⇧' expected after '"'
Skipping line 101198: '⇧' expected after '"'
Skipping line 101552: '⇧' expected after '"'
Skipping line 104144: '⇧' expected after '"'
Skipping line 104426: '⇧' expected after '"'
Skipping line 104858: '⇧' expected after '"'
Skipping line 105034: '⇧' expected after '"'
Skipping line 105340: '⇧' expected after '"'
Skipping line 106422: '⇧' expected after '"'
Skipping line 109299: '⇧' expected after '"'
Skipping line 111595: '⇧' expected after '"'
Skipping line 111746: '⇧' expected after '"'
Skipping line 112217: '⇧' expected after '"'
Skipping line 114203: '⇧' expected after '"'
Skipping line 114546: '⇧' expected after '"'
Skipping line 114768: '⇧' expected after '"'
Skipping line 117562: '⇧' expected after '"'
Skipping line 118724: '⇧' expected after '"'
Skipping line 119663: '⇧' expected after '"'
Skipping line 119884: '⇧' expected after '"'
Skipping line 120204: '⇧' expected after '"'
Skipping line 120531: '⇧' expected after '"'
Skipping line 120532: '⇧' expected after '"'
Skipping line 120533: '⇧' expected after '"'
Skipping line 121166: '⇧' expected after '"'
Skipping line 121824: '⇧' expected after '"'
Skipping line 122013: '⇧' expected after '"'
Skipping line 122249: '⇧' expected after '"'

In [4]:
df_data_filter = df_data[~df_data["column_data"].isna()]
df_data_filter

,table_id,column_id,column_data
0,dataset/Dataset/data/1000006/table_0,0,Театр им. Евгения Вахтангова (Москва) Театр им...
1,dataset/Dataset/data/1000007/table_1,2,"Кулагин и партнёры Люба, дети и завод… Врачебн..."
2,dataset/Dataset/data/1000023/table_0,0,1997 2002 2003 2003 2006—2007 2008 2010 2010 2...
3,dataset/Dataset/data/1000078/table_0,2,смешная жизни(Таисия)Приезжая Летняя поездка к...
4,dataset/Dataset/data/1000247/table_0,2,Семейные страсти В пасти безумия Гаррисон Берж...
...,...,...,...
122940,dataset/Dataset/data/999585/table_0,2,Трек-лист [7] № Название Длительность 1. «Анге...
122941,dataset/Dataset/data/999746/table_3,20,НКЛ НКЛ
122942,dataset/Dataset/data/999874/table_0,5,5 из 9 8½ из 17 14 из 18 4½ из 15 14½ из 19 7 ...
122943,dataset/Dataset/data/999913/table_1,0,28-4-1 28-3-1 28-2-1 28-2 28-1 27-1 26-1 25-1 ...
122944,dataset/Dataset/data/999985/table_0,2,71-й чемпионат Украины 73-й чемпионат Украины ...

## Очистка мета-информации

- Очищена мета-информация .mv-parser...
- Очищены ссылки типа ***some-text[1]***.

### .mw-parser

In [5]:
mv_parser = df_data_filter["column_data"].str.contains(".mw-parser")
df_data_filter[mv_parser]

,table_id,column_id,column_data
166,dataset/Dataset/data/1009955/table_1,5,22 февраля 1993.mw-parser-output .ts-comment-c...
171,dataset/Dataset/data/1010117/table_1,5,22 февраля 1993.mw-parser-output .ts-comment-c...
582,dataset/Dataset/data/1035911/table_1,2,.mw-parser-output .ts-comment-commentedText{bo...
3556,dataset/Dataset/data/1066312/table_0,1,1991 1992 1993 1994 1995 1996 1997 1998 2001 2...
5596,dataset/Dataset/data/12157/table_1,0,Истории Изгой-один Хан Соло Прочие спин-оффы Э...
...,...,...,...
121631,dataset/Dataset/data/919988/table_0,12,6-е место из 8 2-е место из 3 Переход на 3-й у...
121854,dataset/Dataset/data/932005/table_2,7,42/48либо40/44 42/48либо40/44 42/48либо40/44 4...
122085,dataset/Dataset/data/944485/table_2,1,«ЖАRA» «Чайный пьяница» «Рвы» GTA 4 (видеоигра...
122407,dataset/Dataset/data/970269/table_1,5,22 февраля 1993.mw-parser-output .ts-comment-c...
122665,dataset/Dataset/data/984371/table_1,5,22 февраля 1993.mw-parser-output .ts-comment-c...

In [6]:
df_data_filter.loc[:, "column_data"] = df_data_filter["column_data"].progress_apply(
    lambda x: re.sub(r"\.mw-parser-output \.ts.+{.+}", "", x)
)
df_data_filter["column_data"].str.contains("mw-parser").sum()

100%|████████████████████████████| 1447089/1447089 [00:01<00:00, 1048462.61it/s]

0

In [7]:
# def clean_mv_parser(col_name: str) -> str:
#     if col_name.strip().startswith(".mw-parser"):
#         return col_name.split("}")[-1]
#     return col_name

# df_data_filter.loc[:, "column_data"] = df_data_filter["column_data"].progress_apply(lambda x: clean_mv_parser(str(x)))
# df_data_filter

In [8]:
df_data_filter[mv_parser]

,table_id,column_id,column_data
166,dataset/Dataset/data/1009955/table_1,5,22 февраля 199328 ноября 1997[13]1 декабря 199...
171,dataset/Dataset/data/1010117/table_1,5,22 февраля 199328 ноября 1997[13]1 декабря 199...
582,dataset/Dataset/data/1035911/table_1,2,22 декабря 2005[6]18 декабря 2020[7]
3556,dataset/Dataset/data/1066312/table_0,1,1991 1992 1993 1994 1995 1996 1997 1998 2001 2...
5596,dataset/Dataset/data/12157/table_1,0,Истории Изгой-один Хан Соло Прочие спин-оффы Э...
...,...,...,...
121631,dataset/Dataset/data/919988/table_0,12,6-е место из 8 2-е место из 3 Переход на 3-й у...
121854,dataset/Dataset/data/932005/table_2,7,42/48либо40/44 42/48либо40/44 42/48либо40/44 4...
122085,dataset/Dataset/data/944485/table_2,1,«ЖАRA» «Чайный пьяница» «Рвы» GTA 4 (видеоигра...
122407,dataset/Dataset/data/970269/table_1,5,22 февраля 199328 ноября 1997[13]1 декабря 199...
122665,dataset/Dataset/data/984371/table_1,5,22 февраля 199328 ноября 1997[13]1 декабря 199...

### Ссылки википедии

In [9]:
import re

df_data_filter.loc[:, "column_data"] = df_data_filter["column_data"].progress_apply(lambda x: re.sub(r"\[[0-9]*\]", "", x))
df_data_filter

100%|█████████████████████████████| 1447089/1447089 [00:01<00:00, 992605.77it/s]

,table_id,column_id,column_data
0,dataset/Dataset/data/1000006/table_0,0,Театр им. Евгения Вахтангова (Москва) Театр им...
1,dataset/Dataset/data/1000007/table_1,2,"Кулагин и партнёры Люба, дети и завод… Врачебн..."
2,dataset/Dataset/data/1000023/table_0,0,1997 2002 2003 2003 2006—2007 2008 2010 2010 2...
3,dataset/Dataset/data/1000078/table_0,2,смешная жизни(Таисия)Приезжая Летняя поездка к...
4,dataset/Dataset/data/1000247/table_0,2,Семейные страсти В пасти безумия Гаррисон Берж...
...,...,...,...
122940,dataset/Dataset/data/999585/table_0,2,Трек-лист № Название Длительность 1. «Ангел м...
122941,dataset/Dataset/data/999746/table_3,20,НКЛ НКЛ
122942,dataset/Dataset/data/999874/table_0,5,5 из 9 8½ из 17 14 из 18 4½ из 15 14½ из 19 7 ...
122943,dataset/Dataset/data/999913/table_1,0,28-4-1 28-3-1 28-2-1 28-2 28-1 27-1 26-1 25-1 ...
122944,dataset/Dataset/data/999985/table_0,2,71-й чемпионат Украины 73-й чемпионат Украины ...

In [10]:
empty_column_data_mask = df_data_filter["column_data"].apply(lambda x: str(x).replace(";", "").strip()) == ""

In [11]:
df_data_filter = df_data_filter[~empty_column_data_mask]

## JOIN заголовков с содержимым столбца

создание композитного ключа и merge(inner) двух датафреймов

### ColumnData dataframe

In [12]:
df_data_filter.loc[:, "composite_key"] = df_data_filter["table_id"] + " / " + df_data_filter["column_id"].astype(str)
df_data_filter

/tmp/ipykernel_19157/3755119166.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_data_filter.loc[:, "composite_key"] = df_data_filter["table_id"] + " / " + df_data_filter["column_id"].astype(str)

,table_id,column_id,column_data,composite_key
0,dataset/Dataset/data/1000006/table_0,0,Театр им. Евгения Вахтангова (Москва) Театр им...,dataset/Dataset/data/1000006/table_0 / 0
1,dataset/Dataset/data/1000007/table_1,2,"Кулагин и партнёры Люба, дети и завод… Врачебн...",dataset/Dataset/data/1000007/table_1 / 2
2,dataset/Dataset/data/1000023/table_0,0,1997 2002 2003 2003 2006—2007 2008 2010 2010 2...,dataset/Dataset/data/1000023/table_0 / 0
3,dataset/Dataset/data/1000078/table_0,2,смешная жизни(Таисия)Приезжая Летняя поездка к...,dataset/Dataset/data/1000078/table_0 / 2
4,dataset/Dataset/data/1000247/table_0,2,Семейные страсти В пасти безумия Гаррисон Берж...,dataset/Dataset/data/1000247/table_0 / 2
...,...,...,...,...
122940,dataset/Dataset/data/999585/table_0,2,Трек-лист № Название Длительность 1. «Ангел м...,dataset/Dataset/data/999585/table_0 / 2
122941,dataset/Dataset/data/999746/table_3,20,НКЛ НКЛ,dataset/Dataset/data/999746/table_3 / 20
122942,dataset/Dataset/data/999874/table_0,5,5 из 9 8½ из 17 14 из 18 4½ из 15 14½ из 19 7 ...,dataset/Dataset/data/999874/table_0 / 5
122943,dataset/Dataset/data/999913/table_1,0,28-4-1 28-3-1 28-2-1 28-2 28-1 27-1 26-1 25-1 ...,dataset/Dataset/data/999913/table_1 / 0
122944,dataset/Dataset/data/999985/table_0,2,71-й чемпионат Украины 73-й чемпионат Украины ...,dataset/Dataset/data/999985/table_0 / 2

### Threshold dataframe

In [13]:
threshold = 0.78
df_threshold = pd.read_csv(f"../labelling/labelled/threshold_{threshold}.csv", sep=";")
df_threshold

,table_id,column_id,column_name_lemma,label,similarity
0,dataset/Dataset/data/1000006/table_0,0,театр,театр,1.000000
1,dataset/Dataset/data/1000006/table_0,1,спектакль,пьеса,0.789814
2,dataset/Dataset/data/1000006/table_0,4,примечание,примечание,1.000000
3,dataset/Dataset/data/1000006/table_1,0,год,год,1.000000
4,dataset/Dataset/data/1000006/table_1,2,название,название,1.000000
...,...,...,...,...,...
1504994,dataset/Dataset/data/999987/table_0,6,результат,результат,1.000000
1504995,dataset/Dataset/data/999987/table_0,2,турнир,турнир,1.000000
1504996,dataset/Dataset/data/999987/table_0,1,город,город,1.000000
1504997,dataset/Dataset/data/999987/table_0,0,год,год,1.000000
1504998,dataset/Dataset/data/999987/table_0,7,место,место,1.000000

In [14]:
df_threshold.drop(["column_name_lemma", "similarity"], axis=1, inplace=True)
df_threshold

                                     table_id  column_id       label
0        dataset/Dataset/data/1000006/table_0          0       театр
1        dataset/Dataset/data/1000006/table_0          1       пьеса
2        dataset/Dataset/data/1000006/table_0          4  примечание
3        dataset/Dataset/data/1000006/table_1          0         год
4        dataset/Dataset/data/1000006/table_1          2    название
...                                       ...        ...         ...
1504994   dataset/Dataset/data/999987/table_0          6   результат
1504995   dataset/Dataset/data/999987/table_0          2      турнир
1504996   dataset/Dataset/data/999987/table_0          1       город
1504997   dataset/Dataset/data/999987/table_0          0         год
1504998   dataset/Dataset/data/999987/table_0          7       место

[1504999 rows x 3 columns]

In [15]:
df_threshold.loc[:, "composite_key"] = df_threshold["table_id"] + " / " + df_threshold["column_id"].astype(str)
df_threshold

,table_id,column_id,label,composite_key
0,dataset/Dataset/data/1000006/table_0,0,театр,dataset/Dataset/data/1000006/table_0 / 0
1,dataset/Dataset/data/1000006/table_0,1,пьеса,dataset/Dataset/data/1000006/table_0 / 1
2,dataset/Dataset/data/1000006/table_0,4,примечание,dataset/Dataset/data/1000006/table_0 / 4
3,dataset/Dataset/data/1000006/table_1,0,год,dataset/Dataset/data/1000006/table_1 / 0
4,dataset/Dataset/data/1000006/table_1,2,название,dataset/Dataset/data/1000006/table_1 / 2
...,...,...,...,...
1504994,dataset/Dataset/data/999987/table_0,6,результат,dataset/Dataset/data/999987/table_0 / 6
1504995,dataset/Dataset/data/999987/table_0,2,турнир,dataset/Dataset/data/999987/table_0 / 2
1504996,dataset/Dataset/data/999987/table_0,1,город,dataset/Dataset/data/999987/table_0 / 1
1504997,dataset/Dataset/data/999987/table_0,0,год,dataset/Dataset/data/999987/table_0 / 0
1504998,dataset/Dataset/data/999987/table_0,7,место,dataset/Dataset/data/999987/table_0 / 7

### Join dataframes

In [16]:
df_joined = df_threshold.merge(df_data_filter[["composite_key", "column_data"]], how="inner", on="composite_key")
df_joined.drop(["composite_key"], axis=1, inplace=True)
df_joined

,table_id,column_id,label,column_data
0,dataset/Dataset/data/1000006/table_0,0,театр,Театр им. Евгения Вахтангова (Москва) Театр им...
1,dataset/Dataset/data/1000006/table_0,1,пьеса,Дневник Анны ФранкФрэнсис Гудрич и Альберт Хак...
2,dataset/Dataset/data/1000006/table_0,4,примечание,видеофрагмент видеофрагмент телеспектакль виде...
3,dataset/Dataset/data/1000006/table_1,0,год,2004—2013 2006 2006 2006 2008 2007 2007 2008 2...
4,dataset/Dataset/data/1000006/table_1,2,название,"Кулагин и партнёры Люба, дети и завод… Врачебн..."
...,...,...,...,...
1439851,dataset/Dataset/data/999987/table_0,6,результат,7½ из 9 Нокаут-система 6½ из 9 8 из 11 6½ из 1...
1439852,dataset/Dataset/data/999987/table_0,2,турнир,71-й чемпионат Украины 73-й чемпионат Украины ...
1439853,dataset/Dataset/data/999987/table_0,1,город,Алушта Харьков Москва Киев Нью-Дели Киев Львов...
1439854,dataset/Dataset/data/999987/table_0,0,год,2002 2004 2010 2012 2012 2013 2014 2016 2018
1439855,dataset/Dataset/data/999987/table_0,7,место,1 2 2 1 1 3 3 2 1

### Create label_id

In [17]:
labels = list(df_joined["label"].unique())
labels.sort()

sem_types = {v: i for i, v in enumerate(labels)}
sem_types

{'авиакомпания': 0,
 'автомобиль': 1,
 'адрес': 2,
 'актер': 3,
 'альбом': 4,
 'аннотация': 5,
 'арена': 6,
 'атлет': 7,
 'аэропорт': 8,
 'база': 9,
 'банк': 10,
 'боксер': 11,
 'борец': 12,
 'ввп': 13,
 'ведущий': 14,
 'вес': 15,
 'вещество': 16,
 'владелец': 17,
 'возраст': 18,
 'высота': 19,
 'гимнаст': 20,
 'глубина': 21,
 'год': 22,
 'гонка': 23,
 'город': 24,
 'группа': 25,
 'дата': 26,
 'двигатель': 27,
 'день': 28,
 'директор': 29,
 'документ': 30,
 'дорога': 31,
 'жанр': 32,
 'животное': 33,
 'журнал': 34,
 'закон': 35,
 'звук': 36,
 'здание': 37,
 'игра': 38,
 'идентификатор': 39,
 'идеология': 40,
 'издатель': 41,
 'изображение': 42,
 'инструмент': 43,
 'камера': 44,
 'канал': 45,
 'категория': 46,
 'класс': 47,
 'классификация': 48,
 'клуб': 49,
 'книга': 50,
 'код': 51,
 'количество': 52,
 'колледж': 53,
 'команда': 54,
 'компания': 55,
 'компонент': 56,
 'континент': 57,
 'конькобежец': 58,
 'корабль': 59,
 'кратер': 60,
 'лейбл': 61,
 'лес': 62,
 'лига': 63,
 'локомотив': 64,
 'марка': 65,
 'место': 66,
 'местонахождение': 67,
 'модель': 68,
 'мотоцикл': 69,
 'музей': 70,
 'муниципалитет': 71,
 'награда': 72,
 'название': 73,
 'население': 74,
 'национальность': 75,
 'область': 76,
 'образование': 77,
 'опера': 78,
 'оператор': 79,
 'описание': 80,
 'организация': 81,
 'остров': 82,
 'отель': 83,
 'отношение': 84,
 'партия': 85,
 'партнер': 86,
 'период': 87,
 'персона': 88,
 'персонаж': 89,
 'песня': 90,
 'пилот': 91,
 'площадь': 92,
 'поезд': 93,
 'позиция': 94,
 'пол': 95,
 'порт': 96,
 'порядок': 97,
 'правительство': 98,
 'премия': 99,
 'префектура': 100,
 'примечание': 101,
 'провинция': 102,
 'программа': 103,
 'продолжительность': 104,
 'продукт': 105,
 'продюсер': 106,
 'проект': 107,
 'производитель': 108,
 'происхождение': 109,
 'пьеса': 110,
 'работа': 111,
 'работодатель': 112,
 'размер': 113,
 'район': 114,
 'ракета': 115,
 'ранг': 116,
 'расстояние': 117,
 'результат': 118,
 'река': 119,
 'религия': 120,
 'роман': 121,
 'сайт': 122,
 'самолет': 123,
 'символ': 124,
 'сингл': 125,
 'служба': 126,
 'событие': 127,
 'создатель': 128,
 'сообщество': 129,
 'состояние': 130,
 'спорт': 131,
 'спортсмен': 132,
 'ссылка': 133,
 'стадион': 134,
 'стандарт': 135,
 'станция': 136,
 'статистика': 137,
 'статус': 138,
 'статья': 139,
 'столица': 140,
 'страна': 141,
 'структура': 142,
 'судья': 143,
 'сценарист': 144,
 'театр': 145,
 'теннисист': 146,
 'территория': 147,
 'техника': 148,
 'тип': 149,
 'транспорт': 150,
 'требование': 151,
 'трек': 152,
 'тренер': 153,
 'турнир': 154,
 'улица': 155,
 'университет': 156,
 'устройство': 157,
 'фигурист': 158,
 'фильм': 159,
 'фирма': 160,
 'флаг': 161,
 'формат': 162,
 'футболист': 163,
 'художник': 164,
 'цвет': 165,
 'цитата': 166,
 'шахматист': 167,
 'элемент': 168,
 'язык': 169}

In [18]:
df_joined["label_id"] = df_joined["label"].progress_apply(lambda x: sem_types[x])
df_joined

100%|████████████████████████████| 1439856/1439856 [00:00<00:00, 2295547.82it/s]

,table_id,column_id,label,column_data,label_id
0,dataset/Dataset/data/1000006/table_0,0,театр,Театр им. Евгения Вахтангова (Москва) Театр им...,145
1,dataset/Dataset/data/1000006/table_0,1,пьеса,Дневник Анны ФранкФрэнсис Гудрич и Альберт Хак...,110
2,dataset/Dataset/data/1000006/table_0,4,примечание,видеофрагмент видеофрагмент телеспектакль виде...,101
3,dataset/Dataset/data/1000006/table_1,0,год,2004—2013 2006 2006 2006 2008 2007 2007 2008 2...,22
4,dataset/Dataset/data/1000006/table_1,2,название,"Кулагин и партнёры Люба, дети и завод… Врачебн...",73
...,...,...,...,...,...
1439851,dataset/Dataset/data/999987/table_0,6,результат,7½ из 9 Нокаут-система 6½ из 9 8 из 11 6½ из 1...,118
1439852,dataset/Dataset/data/999987/table_0,2,турнир,71-й чемпионат Украины 73-й чемпионат Украины ...,154
1439853,dataset/Dataset/data/999987/table_0,1,город,Алушта Харьков Москва Киев Нью-Дели Киев Львов...,24
1439854,dataset/Dataset/data/999987/table_0,0,год,2002 2004 2010 2012 2012 2013 2014 2016 2018,22
1439855,dataset/Dataset/data/999987/table_0,7,место,1 2 2 1 1 3 3 2 1,66

### Reorder columns

In [19]:
df_joined = df_joined[["table_id", "column_id", "label_id", "label", "column_data"]]
df_joined

,table_id,column_id,label_id,label,column_data
0,dataset/Dataset/data/1000006/table_0,0,145,театр,Театр им. Евгения Вахтангова (Москва) Театр им...
1,dataset/Dataset/data/1000006/table_0,1,110,пьеса,Дневник Анны ФранкФрэнсис Гудрич и Альберт Хак...
2,dataset/Dataset/data/1000006/table_0,4,101,примечание,видеофрагмент видеофрагмент телеспектакль виде...
3,dataset/Dataset/data/1000006/table_1,0,22,год,2004—2013 2006 2006 2006 2008 2007 2007 2008 2...
4,dataset/Dataset/data/1000006/table_1,2,73,название,"Кулагин и партнёры Люба, дети и завод… Врачебн..."
...,...,...,...,...,...
1439851,dataset/Dataset/data/999987/table_0,6,118,результат,7½ из 9 Нокаут-система 6½ из 9 8 из 11 6½ из 1...
1439852,dataset/Dataset/data/999987/table_0,2,154,турнир,71-й чемпионат Украины 73-й чемпионат Украины ...
1439853,dataset/Dataset/data/999987/table_0,1,24,город,Алушта Харьков Москва Киев Нью-Дели Киев Львов...
1439854,dataset/Dataset/data/999987/table_0,0,22,год,2002 2004 2010 2012 2012 2013 2014 2016 2018
1439855,dataset/Dataset/data/999987/table_0,7,66,место,1 2 2 1 1 3 3 2 1

In [20]:
df_joined[df_joined["table_id"] == "dataset/Dataset/data/1367439/table_0"]

,table_id,column_id,label_id,label,column_data
91760,dataset/Dataset/data/1367439/table_0,1,95,пол,неизвестен

In [21]:
column_data_na = df_joined["column_data"].isna().sum()
column_data_na
# df_joined = df_joined[~column_data_na]

0

In [22]:
df_joined

,table_id,column_id,label_id,label,column_data
0,dataset/Dataset/data/1000006/table_0,0,145,театр,Театр им. Евгения Вахтангова (Москва) Театр им...
1,dataset/Dataset/data/1000006/table_0,1,110,пьеса,Дневник Анны ФранкФрэнсис Гудрич и Альберт Хак...
2,dataset/Dataset/data/1000006/table_0,4,101,примечание,видеофрагмент видеофрагмент телеспектакль виде...
3,dataset/Dataset/data/1000006/table_1,0,22,год,2004—2013 2006 2006 2006 2008 2007 2007 2008 2...
4,dataset/Dataset/data/1000006/table_1,2,73,название,"Кулагин и партнёры Люба, дети и завод… Врачебн..."
...,...,...,...,...,...
1439851,dataset/Dataset/data/999987/table_0,6,118,результат,7½ из 9 Нокаут-система 6½ из 9 8 из 11 6½ из 1...
1439852,dataset/Dataset/data/999987/table_0,2,154,турнир,71-й чемпионат Украины 73-й чемпионат Украины ...
1439853,dataset/Dataset/data/999987/table_0,1,24,город,Алушта Харьков Москва Киев Нью-Дели Киев Львов...
1439854,dataset/Dataset/data/999987/table_0,0,22,год,2002 2004 2010 2012 2012 2013 2014 2016 2018
1439855,dataset/Dataset/data/999987/table_0,7,66,место,1 2 2 1 1 3 3 2 1

### Remove stupid .mw-parser ._.

In [23]:
# df_joined.loc[:, "column_data"] = df_joined["column_data"].progress_apply(lambda x: re.sub(r"\.mw-parser-output \.ts.+{.+}", "", x))
df_joined["column_data"].str.contains("mw-parser").sum()

0

In [24]:
df_joined[df_joined["table_id"] == "dataset/Dataset/data/1012855/table_1"]

,table_id,column_id,label_id,label,column_data
2303,dataset/Dataset/data/1012855/table_1,5,26,дата,22 февраля 199328 ноября 19971 декабря 19974 я...
2304,dataset/Dataset/data/1012855/table_1,1,73,название,«Вавилон-5: Сборы» «Babylon 5: The Gathering»
2305,dataset/Dataset/data/1012855/table_1,3,144,сценарист,Дж. Майкл Стражински
2306,dataset/Dataset/data/1012855/table_1,2,3,актер,Ричард Комптон
2307,dataset/Dataset/data/1012855/table_1,7,51,код,0
2308,dataset/Dataset/data/1012855/table_1,4,106,продюсер,Роберт Латман Браун

In [25]:
# tokenizer will take care of it
# df_joined.loc[:, "column_data"] = df_joined["column_data"].progress_apply(lambda x: str(x).lower())

### Save dataset

In [26]:
df_joined.to_csv("./dataset/cta_dataset.csv", sep="|", index=False)

In [27]:
# import numpy as np

# number_of_chunks = 12
# for id, chunk in enumerate(np.array_split(df_joined, number_of_chunks)):
#     chunk.to_csv(f"./data/data_{id}.csv", sep="|", index=False)